backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Design&Install"
    name: "design&install"
    files:
      - name: "design&installExpertise" # Used in routes, e.g., /admin/collections/blog
        label: "Design&Install Expertise" # Used in the UI
        file: "src/pages/design&installExpertise.json"
        fields: # The fields for each document, usually in front matter
          - {
              label: "Expertise text",
              name: "expertise-text",
              widget: "text",
              optional: true,
            }
          - {
              label: "Drawing service text",
              name: "drawing-service-text",
              widget: "text",
              optional: true,
            }
          - {
              label: "Garden design text",
              name: "garden-design-text",
              widget: "text",
              optional: true,
            }
          - {
              label: "Design&Build service text",
              name: "design&build-service-text",
              widget: "text",
              optional: true,
            }

    # - name: "softscaping" # Used in routes, e.g., /admin/collections/blog
    #   label: "Softscaping" # Used in the UI
    #   folder: "src/pages/softscapingCMS" # The path to the folder where the documents are stored
    #   create: true # Allow users to create new documents in this collection
    #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    #   fields: # The fields for each document, usually in front matter
    #     - { label: "Description", name: "description", widget: "string" }

    # - name: "hardscaping" # Used in routes, e.g., /admin/collections/blog
    #   label: "Hardscaping" # Used in the UI
    #   folder: "src/pages/HardscapingCMS" # The path to the folder where the documents are stored
    #   create: true # Allow users to create new documents in this collection
    #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    #   fields: # The fields for each document, usually in front matter
    #     - { label: "Description", name: "description", widget: "string" }

    # - name: "design&install" # Used in routes, e.g., /admin/collections/blog
    #   label: "Design&Install" # Used in the UI
    #   file: "src/pages/design&installCMS.yml" # The path to the folder where the documents are stored
    #   create: true # Allow users to create new documents in this collection
    #   fields: # The fields for each document, usually in front matter
    #     - {
    #         label: "Expertise text",
    #         name: "expertise-text",
    #         widget: "string",
    #         optional: true,
    #       }
    #     - {
    #         label: "Drawing service text",
    #         name: "drawing-service-text",
    #         widget: "string",
    #         optional: true,
    #       }
    #     - {
    #         label: "Garden design text",
    #         name: "garden-design-text",
    #         widget: "string",
    #         optional: true,
    #       }
    #     - {
    #         label: "Design&Build service text",
    #         name: "design&build-service-text",
    #         widget: "string",
    #         optional: true,
    #       }
    # - name: "main-page" # Used in routes, e.g., /admin/collections/blog
    #   label: "Main page" # Used in the UI
    #   folder: "src/pages/softscapingCMS" # The path to the folder where the documents are stored
    #   create: true # Allow users to create new documents in this collection
    #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    #   fields: # The fields for each document, usually in front matter
    #     - { label: "Description", name: "description", widget: "string" }
